function [center, area] = find_largest_blob(img, color)

range = 20;
red_color = color(1); green_color = color(2); blue_color = color(3);

blob_pixel_mask = img(:,:,1) > red_color - range & ...
    img(:,:,1) < red_color + range * ...
    img(:,:,2) > blue_color - range & ...
    img(:,:,2) < blue_color + range & ...
    img(:,:,3) > green_color - range & ...
    img(:,:,3) < green_color + range;

%blob_pixel_mask is 2d array, 

